import Head from "next/head";
import MainContext from "../contexts/Main";
import { useContext } from "react";
import Header from "../containers/Header";
import List from "../containers/List";

export default function TypePokemon({ data, filteredData }) {
  const { hasError } = useContext(MainContext);

    const currentType = data.name
    .split(" ")
    .map((l) => l.charAt(0).toUpperCase() + l.substr(1))
    .join(" ");

  if (hasError) return <p>Une erreur est survenue...</p>;

  return (
    <>
      <Head>
        <title>Pokémons de type</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />


      <List data={filteredData} />
    </>
  );
}

export async function getServerSideProps({ query }) {
  const typeName = query.type;

  try {
    const response = await fetch(`https://pokeapi.co/api/v2/type/${typeName}`);
    if (response.status === 404) {
      const typeNotFound = true;
      return { props: { typeNotFound } };
    }
    const data = await response.json();
    const filteredData = data.pokemon.map((el) => el.pokemon);

    return {
      props: { data, filteredData },
    };
  } catch (err) {
    throw err;
  }
}
