import Head from 'next/head'
import Image from 'next/image'
import style from '../styles/Home.module.scss'
import Header from './containers/Header'

export default function Details({ data }) {
    const { height, id, moves, name, types, weight } = data

    const paddedId = id
    const pkmImg = `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${paddedId}.png`

    return (
        <div>
            <Head>
                <title>Pokedex - {name}</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div className={style.pokemon_detail_container}>
                <div>
                    <h1>{name}</h1>
                    <div className={style.detail_card}>
                        <Image
                            src={pkmImg}
                            alt={name}
                            width={250}
                            height={250}
                        />
                        <p>
                            <span>Poids:</span> {weight / 10} kg
                        </p>
                        <p>
                            <span>Taille:</span> {height / 10} m
                        </p>
                        <h2>Types</h2>
                        {types.map((type, index) => (
                            <p
                                key={index}
                                className={`${style.types__type} ${
                                    style[type.type.name]
                                }`}
                            >
                                {type.type.name}
                            </p>
                        ))}
                        <h2>Attaques</h2>
                        {moves.slice(0, 3).map((ability, index) => (
                            <p key={index} className={style.abilities}>
                                {ability.move.name}
                            </p>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    )
}

export async function getServerSideProps({ query }) {
    const pkmnName = query.slug

    try {
        const response = await fetch(
            `https://pokeapi.co/api/v2/pokemon/${pkmnName}`
        )
        if (response.status === 404) {
            const pkmnNotFound = true
            return { props: { pkmnNotFound } }
        }
        const data = await response.json()

        return {
            props: { data },
        }
    } catch (err) {
        throw err
    }
}
