import Head from 'next/head'
import List from './containers/List';
import style from '../styles/Home.module.scss'
import Header from './containers/Header';
import Form from './containers/Form';
import MainContext from "./contexts/Main";
import Loader from './components/Loader';
import { useContext } from "react";
import TypesList from './types/TypesList';

export default function Home() {

  const { handleChange, filteredData, hasError, isLoading } = useContext(MainContext);
  
  if (hasError) return <p>Une erreur est survenue...</p>;

  return (
    <div className={style.main}>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Form handleChange={handleChange} />
      <TypesList/>
      {isLoading ? <Loader /> : <List data={filteredData} />}
    </div>
  )
}