import Head from 'next/head'
import Link from 'next/link';
import Fetch from './components/Fetch';

export default function Home({pokemon}) {
  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fetch/>
    </div>
  )
}

// export const getStaticProps = async () => {
//   const res = await fetch('https://pokeapi.co/api/v2/pokemon?limit=151');
//   const {results} = await res.json();
//   const pokemon = results.map((pokeman, index) => {
//     const paddedId = ('00' + (index + 1)).slice(-3);
//     const image = `https://assets.pokemon.com/assets/cms2/img/pokedex/detail/${paddedId}.png`;
//     return {...pokeman, image};
//   });
//   return {
//     props: {pokemon},
//   };
// }